// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqGjAF2Fvu4yA4FPv0VXxSUf-aMqXq6so',
    appId: '1:493630785851:web:ca70814cb0d8c874edcf1e',
    messagingSenderId: '493630785851',
    projectId: 'level-36ac1',
    authDomain: 'level-36ac1.firebaseapp.com',
    storageBucket: 'level-36ac1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpsNjcbWBqYAasv4n3IcZtBT7Rn3JYHA',
    appId: '1:493630785851:android:d89d8691c3d75c49edcf1e',
    messagingSenderId: '493630785851',
    projectId: 'level-36ac1',
    storageBucket: 'level-36ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdnDRlr5AVsrzEfrm5HQ20zk3FYUOEcwI',
    appId: '1:493630785851:ios:759cea3e91dbcabdedcf1e',
    messagingSenderId: '493630785851',
    projectId: 'level-36ac1',
    storageBucket: 'level-36ac1.appspot.com',
    iosBundleId: 'com.example.level',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdnDRlr5AVsrzEfrm5HQ20zk3FYUOEcwI',
    appId: '1:493630785851:ios:0c3d6a0b30e0c9baedcf1e',
    messagingSenderId: '493630785851',
    projectId: 'level-36ac1',
    storageBucket: 'level-36ac1.appspot.com',
    iosBundleId: 'com.example.level.RunnerTests',
  );
}
